#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=4
ENV_FILE="${ENV_FILE:-.env}"

GITHUB_ORG="chidioguejiofor"
SERVERLESS_REPO="sureplug-serverless"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
POLICY_FILE="$SCRIPT_DIR/../../deploy-config/ci-deploy-policy.json"
PERMISSIONS_POLICY_NAME="sureplug-serverless-ci-deploy"
ROLE_NAMES=(
  "sureplug-serverless-deploy-staging"
  "sureplug-serverless-deploy-production"
)
ROLE_ENVS=(
  "staging"
  "production"
)
ROLE_ENV_KEYS=(
  "DEPLOY_ROLE_ARN_SERVERLESS_STAGING"
  "DEPLOY_ROLE_ARN_SERVERLESS_PRODUCTION"
)

banner "AWS: GitHub OIDC deploy IAM roles"
say "This creates the 2 IAM roles that let GitHub Actions deploy sureplug-serverless"
say "to staging/production — trust-scoped to a specific repo + GitHub Environment,"
say "so the IAM trust boundary and the Environment's required-reviewer approval"
say "reinforce each other."
note "sureplug-backend provisions its own deploy IAM roles from its own"
note "scripts/aws/create-deploy-iam-roles.sh - this script is serverless-only."
note "Unlike backend's EB-targeted policy, deploy-config/ci-deploy-policy.json"
note "here is already a complete, literal document (Lambda/CloudFormation/S3/"
note "Step Functions, scoped to the sureplug-media-pipeline service) - no"
note "placeholder substitution needed, so it's applied as-is."

# ── Stage 1: sign in ────────────────────────────────────────────────────────
stage "Sign in to AWS (aws login)"
say "Same sign-in flow as sureplug-backend's equivalent script. If your"
say "session from that run is still active (sessions last up to 12h), this"
say "will skip straight through."

if ! command -v aws >/dev/null 2>&1; then
  warn "aws CLI not found on PATH."
  say "Install it, then re-run this script:"
  step "macOS: brew install awscli"
  step "Docs:  https://docs.aws.amazon.com/cli/latest/userguide/getting-started-install.html"
  exit 1
fi
note "aws CLI found: $(command -v aws)"

ask AWS_PROFILE_NAME "Profile name to use for SurePlug [sureplug]:"
AWS_PROFILE_NAME="${AWS_PROFILE_NAME:-sureplug}"
export AWS_PROFILE="$AWS_PROFILE_NAME"
note "Using AWS_PROFILE=$AWS_PROFILE"

if ! CALLER_JSON=$(aws sts get-caller-identity --output json 2>&1); then
  say "Not signed in yet under profile '$AWS_PROFILE'."
  pause "Press Enter to run 'aws login --profile $AWS_PROFILE'..."
  if ! aws login --profile "$AWS_PROFILE"; then
    warn "'aws login' did not complete."
    say "Re-run this script once you've signed in."
    exit 1
  fi
  if ! CALLER_JSON=$(aws sts get-caller-identity --output json 2>&1); then
    warn "Still not authenticated after aws login:"
    note "$CALLER_JSON"
    exit 1
  fi
fi

ACCOUNT_ID=$(printf '%s' "$CALLER_JSON" | grep -o '"Account"[^,}]*' | grep -o '[0-9]\{12\}')
CALLER_ARN=$(printf '%s' "$CALLER_JSON" | grep -o '"Arn"[^,}]*' | sed -E 's/.*"Arn"[[:space:]]*:[[:space:]]*"([^"]+)".*/\1/')
say "Authenticated as:"
note "  Profile:  $AWS_PROFILE"
note "  Account:  $ACCOUNT_ID"
note "  Identity: $CALLER_ARN"
warn "Double-check this is the correct SurePlug AWS account before continuing."
if ! confirm "Is this the right AWS account for SurePlug staging/production?"; then
  say "Stopping. Run 'aws logout --profile $AWS_PROFILE', sign in as the right"
  say "identity with 'aws login --profile $AWS_PROFILE', and re-run."
  exit 1
fi
write_env AWS_PROFILE_NAME "$AWS_PROFILE_NAME"

# ── Stage 2: locate the OIDC provider ───────────────────────────────────────
stage "Locate the GitHub OIDC provider"
say "Each role's trust policy federates to this provider. sureplug-backend's"
say "scripts/aws/create-github-oidc-provider.sh creates it once per AWS"
say "account - the same provider is shared across every repo's deploy roles."

EXISTING_ARNS=$(aws iam list-open-id-connect-providers --query 'OpenIDConnectProviderList[].Arn' --output text 2>/dev/null || true)
OIDC_PROVIDER_ARN=""
if [[ -n "$EXISTING_ARNS" ]]; then
  OIDC_PROVIDER_ARN=$(printf '%s\n' "$EXISTING_ARNS" | tr '\t' '\n' | grep 'token.actions.githubusercontent.com' | head -n1 || true)
fi

if [[ -z "$OIDC_PROVIDER_ARN" ]]; then
  warn "No GitHub OIDC provider found in account $ACCOUNT_ID."
  say "Run sureplug-backend's scripts/aws/create-github-oidc-provider.sh"
  say "first, then re-run this script."
  exit 1
fi
note "Found: $OIDC_PROVIDER_ARN"

# ── Stage 3: create/update the 2 roles ──────────────────────────────────────
stage "Create the 2 deploy IAM roles + trust policies"
say "Each trust policy allows sts:AssumeRoleWithWebIdentity only for GitHub"
say "Actions jobs whose OIDC token has this exact subject claim:"
note "  <repo OIDC subject prefix>:environment:<staging|production>"
note "  (the prefix is read from GitHub, since newer repos use immutable numeric IDs)"
say ""
say "Roles to create/update in account $ACCOUNT_ID:"
for i in "${!ROLE_NAMES[@]}"; do
  note "  ${ROLE_NAMES[$i]}  (repo:$GITHUB_ORG/$SERVERLESS_REPO:environment:${ROLE_ENVS[$i]})"
done
say ""
say "Each role also gets $POLICY_FILE applied as-is"
say "(inline policy $PERMISSIONS_POLICY_NAME)."

if [[ ! -f "$POLICY_FILE" ]]; then
  warn "$POLICY_FILE not found - run this script from the repo it ships in."
  exit 1
fi

if ! confirm "Create/update these 2 roles now?"; then
  say "Stopping without changes."
  exit 1
fi

TMP_DIR=$(mktemp -d)
trap 'rm -rf "$TMP_DIR"' EXIT

oidc_subject_prefix() {
  local repo="$1" prefix
  if ! command -v gh >/dev/null 2>&1; then
    printf 'gh CLI not found on PATH'
    return 1
  fi
  if ! prefix=$(gh api "repos/$repo/actions/oidc/customization/sub" \
        --jq 'select(.use_immutable_subject) | .sub_claim_prefix' 2>&1); then
    printf '%s' "$prefix"
    return 1
  fi
  printf '%s' "${prefix:-repo:$repo}"
}

attach_permissions_policy() {
  local role_name="$1"
  if ! PUT_ERR=$(aws iam put-role-policy \
        --role-name "$role_name" \
        --policy-name "$PERMISSIONS_POLICY_NAME" \
        --policy-document "file://$POLICY_FILE" 2>&1); then
    warn "Failed to attach $PERMISSIONS_POLICY_NAME to $role_name:"
    note "$PUT_ERR"
    exit 1
  fi
  printf '  %s✓ attached%s %s to %s\n' "$GREEN" "$RESET" "$PERMISSIONS_POLICY_NAME" "$role_name"
}

for i in "${!ROLE_NAMES[@]}"; do
  name="${ROLE_NAMES[$i]}"
  repo="$GITHUB_ORG/$SERVERLESS_REPO"
  envname="${ROLE_ENVS[$i]}"
  if ! subject_prefix=$(oidc_subject_prefix "$repo"); then
    warn "Could not read the GitHub OIDC subject for $repo:"
    note "$subject_prefix"
    say "Refusing to write a trust policy that GitHub's tokens would not match."
    say "Run 'gh auth login' (or 'gh auth status' to see which account is broken) and re-run."
    exit 1
  fi
  subject="$subject_prefix:environment:$envname"
  note "Trust subject for $name: $subject"
  policy_file="$TMP_DIR/$name.json"

  cat > "$policy_file" <<JSON
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Principal": { "Federated": "$OIDC_PROVIDER_ARN" },
      "Action": "sts:AssumeRoleWithWebIdentity",
      "Condition": {
        "StringEquals": {
          "token.actions.githubusercontent.com:aud": "sts.amazonaws.com",
          "token.actions.githubusercontent.com:sub": "$subject"
        }
      }
    }
  ]
}
JSON

  if aws iam get-role --role-name "$name" >/dev/null 2>&1; then
    note "Role $name already exists — updating its trust policy."
    if ! UPDATE_ERR=$(aws iam update-assume-role-policy --role-name "$name" --policy-document "file://$policy_file" 2>&1); then
      warn "Failed to update trust policy for $name:"
      note "$UPDATE_ERR"
      exit 1
    fi
    printf '  %s✓ updated%s trust policy for %s\n' "$GREEN" "$RESET" "$name"
  else
    say "Creating $name..."
    if ! CREATE_ERR=$(aws iam create-role \
          --role-name "$name" \
          --assume-role-policy-document "file://$policy_file" \
          --description "GitHub Actions OIDC deploy role: $repo ($envname)" \
          --tags Key=Project,Value=SurePlug Key=Repo,Value="$SERVERLESS_REPO" Key=Environment,Value="$envname" \
          --output json 2>&1); then
      warn "Failed to create $name:"
      note "$CREATE_ERR"
      say "Common cause: your IAM identity lacks iam:CreateRole / iam:TagRole."
      exit 1
    fi
    printf '  %s✓ created%s %s\n' "$GREEN" "$RESET" "$name"
  fi
  attach_permissions_policy "$name"
  aws iam tag-role --role-name "$name" \
    --tags Key=Project,Value=SurePlug Key=Repo,Value="$SERVERLESS_REPO" Key=Environment,Value="$envname" \
    >/dev/null 2>&1 || true
done

# ── Stage 4: verify + record ARNs ───────────────────────────────────────────
stage "Verify and record role ARNs"
say "Reading back each role to confirm it exists and capture its ARN."

for i in "${!ROLE_NAMES[@]}"; do
  name="${ROLE_NAMES[$i]}"
  key="${ROLE_ENV_KEYS[$i]}"
  if ! ROLE_JSON=$(aws iam get-role --role-name "$name" --output json 2>&1); then
    warn "Could not read back $name:"
    note "$ROLE_JSON"
    exit 1
  fi
  arn=$(printf '%s' "$ROLE_JSON" | grep -o '"Arn"[^,}]*' | head -n1 | sed -E 's/.*"Arn"[[:space:]]*:[[:space:]]*"([^"]+)".*/\1/')
  note "$name → $arn"
  write_env "$key" "$arn"
done

finish
