#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=3

banner "AWS: Serverless Framework deployment bucket"
say "Provisions the S3 bucket Serverless Framework v4 uploads deploy artifacts"
say "to, for one stage (staging or production)."
note "Safe to re-run: bucket creation and versioning are both idempotent."
note "IAM policy attachment for the deploy role lives in sureplug-backend's"
note "scripts/aws/create-deploy-iam-roles.sh, not here - run that for permissions."

# ── Stage 1: sign in ─────────────────────────────────────────────────────────
stage "Sign in to AWS (aws login)"
say "Same sign-in as this repo's other scripts/aws/*.sh scripts - if you've"
say "already signed in recently, this skips through."

if ! command -v aws >/dev/null 2>&1; then
  warn "aws CLI not found on PATH."
  say "Install it, then re-run this script:"
  step "macOS: brew install awscli"
  step "Docs:  https://docs.aws.amazon.com/cli/latest/userguide/getting-started-install.html"
  exit 1
fi
note "aws CLI found: $(command -v aws)"

ask AWS_PROFILE_NAME "Profile name to use for SurePlug [sureplug]:"
AWS_PROFILE_NAME="${AWS_PROFILE_NAME:-sureplug}"
export AWS_PROFILE="$AWS_PROFILE_NAME"
note "Using AWS_PROFILE=$AWS_PROFILE"

if ! CALLER_JSON=$(aws sts get-caller-identity --output json 2>&1); then
  say "Not signed in yet under profile '$AWS_PROFILE'."
  pause "Press Enter to run 'aws login --profile $AWS_PROFILE'..."
  if ! aws login --profile "$AWS_PROFILE"; then
    warn "'aws login' did not complete."
    say "Re-run this script once you've signed in."
    exit 1
  fi
  if ! CALLER_JSON=$(aws sts get-caller-identity --output json 2>&1); then
    warn "Still not authenticated after aws login:"
    note "$CALLER_JSON"
    exit 1
  fi
fi

CALLER_ARN=$(printf '%s' "$CALLER_JSON" | grep -o '"Arn"[^,}]*' | sed -E 's/.*"Arn"[[:space:]]*:[[:space:]]*"([^"]+)".*/\1/')
say "Authenticated as:"
note "  Profile:  $AWS_PROFILE"
note "  Identity: $CALLER_ARN"
if ! confirm "Is this the right AWS identity/account for SurePlug?"; then
  say "Stopping. Run 'aws logout --profile $AWS_PROFILE', sign in as the right"
  say "identity with 'aws login --profile $AWS_PROFILE', and re-run."
  exit 1
fi
write_env AWS_PROFILE_NAME "$AWS_PROFILE_NAME"

ask AWS_REGION_NAME "AWS region [eu-west-2]:"
AWS_REGION_NAME="${AWS_REGION_NAME:-eu-west-2}"
export AWS_DEFAULT_REGION="$AWS_REGION_NAME"
write_env AWS_REGION "$AWS_REGION_NAME"

# ── Stage 2: which environment ───────────────────────────────────────────────
stage "Choose the environment"

say "This run provisions exactly one stage's bucket and role. Re-run the"
say "script later for the other one - staging and production are fully"
say "independent here."
while true; do
  ask TARGET_STAGE "Which environment: staging or production?"
  case "$TARGET_STAGE" in
    staging|production) break ;;
    *) warn "Type exactly 'staging' or 'production'." ;;
  esac
done
BUCKET_NAME="sureplug-serverless-deployment-${TARGET_STAGE}"
note "Working on: $TARGET_STAGE"
note "  Bucket: $BUCKET_NAME"

# ── Stage 3: provision the bucket ────────────────────────────────────────────
stage "Provision $TARGET_STAGE bucket"

say "Checking whether $BUCKET_NAME already exists..."
if aws s3api head-bucket --bucket "$BUCKET_NAME" 2>/dev/null; then
  note "Bucket already exists - skipping creation."
else
  say "Creating bucket $BUCKET_NAME in $AWS_REGION_NAME..."
  if CREATE_ERR=$(aws s3api create-bucket \
        --bucket "$BUCKET_NAME" \
        --region "$AWS_REGION_NAME" \
        --create-bucket-configuration LocationConstraint="$AWS_REGION_NAME" 2>&1); then
    printf '  %s✓ created%s bucket %s\n' "$GREEN" "$RESET" "$BUCKET_NAME"
  else
    warn "Failed to create bucket $BUCKET_NAME:"
    note "$CREATE_ERR"
    SKIPPED+=("S3 bucket $BUCKET_NAME (create it by hand, then re-run)")
  fi
fi

say "Enabling versioning on $BUCKET_NAME (required by Serverless's code"
say "storage mode; safe to re-run even if already enabled)..."
if VERSION_ERR=$(aws s3api put-bucket-versioning \
      --bucket "$BUCKET_NAME" \
      --versioning-configuration Status=Enabled 2>&1); then
  printf '  %s✓ versioning enabled%s on %s\n' "$GREEN" "$RESET" "$BUCKET_NAME"
else
  warn "Failed to enable versioning on $BUCKET_NAME:"
  note "$VERSION_ERR"
  SKIPPED+=("S3 versioning on $BUCKET_NAME (enable it by hand)")
fi

say ""
say "Next:"
say "  - Re-run this script with the other stage whenever its bucket is ready"
say "    to be provisioned too."
say "  - Run sureplug-backend's scripts/aws/create-deploy-iam-roles.sh (or"
say "    re-run it) to attach deploy-config/ci-deploy-policy.json - which"
say "    grants access to this bucket - to the sureplug-serverless-deploy-$TARGET_STAGE role."

finish
