#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=3
ENV_FILE="${ENV_FILE:-.env}"
APP_NAME="sureplug-serverless"

# Source-of-truth list of deploy-time secrets that live in Secrets Manager
# instead of GitHub Actions secrets. Kept in sync with the "Fetch secrets
# from AWS Secrets Manager" step in .github/workflows/test.yml and
# promote-production.yml - add a name here and to both workflow steps
# together, never one without the other.
SECRET_VALUE_NAMES=(
  SERVERLESS_ACCESS_KEY
  REPLICATE_API_TOKEN
  REPLICATE_WEBHOOK_SECRET
  MEDIA_PIPELINE_WEBHOOK_SECRET
  NOTIFICATION_DISPATCH_SECRET
)

banner "AWS: Secrets Manager deploy config"
say "Populates one AWS Secrets Manager secret (staging or production — you'll"
say "be asked which) with the values .github/workflows/*.yml fetches at"
say "deploy time, after assuming the deploy IAM role via OIDC — GitHub Actions"
say "itself never stores or sees these values."
note "Safe to re-run: existing values in the secret are offered back as"
note "defaults (Enter keeps them), same as every other wizard here."

# ── Stage 1: sign in ─────────────────────────────────────────────────────────
stage "Sign in to AWS (aws login)"
say "Same sign-in as sureplug-backend's scripts/aws/*.sh scripts — if you've"
say "already signed in there recently, this skips through."

if ! command -v aws >/dev/null 2>&1; then
  warn "aws CLI not found on PATH."
  say "Install it, then re-run this script:"
  step "macOS: brew install awscli"
  step "Docs:  https://docs.aws.amazon.com/cli/latest/userguide/getting-started-install.html"
  exit 1
fi
note "aws CLI found: $(command -v aws)"

ask AWS_PROFILE_NAME "Profile name to use for SurePlug [sureplug]:"
AWS_PROFILE_NAME="${AWS_PROFILE_NAME:-sureplug}"
export AWS_PROFILE="$AWS_PROFILE_NAME"
note "Using AWS_PROFILE=$AWS_PROFILE"

if ! CALLER_JSON=$(aws sts get-caller-identity --output json 2>&1); then
  say "Not signed in yet under profile '$AWS_PROFILE'."
  pause "Press Enter to run 'aws login --profile $AWS_PROFILE'..."
  if ! aws login --profile "$AWS_PROFILE"; then
    warn "'aws login' did not complete."
    say "Re-run this script once you've signed in."
    exit 1
  fi
  if ! CALLER_JSON=$(aws sts get-caller-identity --output json 2>&1); then
    warn "Still not authenticated after aws login:"
    note "$CALLER_JSON"
    exit 1
  fi
fi

CALLER_ARN=$(printf '%s' "$CALLER_JSON" | grep -o '"Arn"[^,}]*' | sed -E 's/.*"Arn"[[:space:]]*:[[:space:]]*"([^"]+)".*/\1/')
say "Authenticated as:"
note "  Profile:  $AWS_PROFILE"
note "  Identity: $CALLER_ARN"
if ! confirm "Is this the right AWS identity/account for SurePlug?"; then
  say "Stopping. Run 'aws logout --profile $AWS_PROFILE', sign in as the right"
  say "identity with 'aws login --profile $AWS_PROFILE', and re-run."
  exit 1
fi
write_env AWS_PROFILE_NAME "$AWS_PROFILE_NAME"

ask AWS_REGION_NAME "AWS region [eu-west-2]:"
AWS_REGION_NAME="${AWS_REGION_NAME:-eu-west-2}"
export AWS_DEFAULT_REGION="$AWS_REGION_NAME"
write_env AWS_REGION "$AWS_REGION_NAME"

# ── Stage 2: which environment ───────────────────────────────────────────────
stage "Choose the environment"

say "This run fills in exactly one secret. Re-run the script later for the"
say "other one — staging and production are fully independent here."
while true; do
  ask TARGET_STAGE "Which environment: staging or production?"
  case "$TARGET_STAGE" in
    staging|production) break ;;
    *) warn "Type exactly 'staging' or 'production'." ;;
  esac
done
SECRET_NAME="${APP_NAME}/${TARGET_STAGE}"
note "Working on: $TARGET_STAGE (secret: $SECRET_NAME)"

# ── Stage 3: fill in the secret's values ─────────────────────────────────────
stage "Set $TARGET_STAGE values"

say "Every value below is hidden input and goes straight into Secrets"
say "Manager, never a GitHub secret. Two of them must match a value that"
say "already exists elsewhere — get those right or deploys will silently"
say "talk past each other instead of failing loudly."

EXISTING_SECRET_JSON=""
if EXISTING_SECRET_JSON=$(aws secretsmanager get-secret-value \
      --secret-id "$SECRET_NAME" --query 'SecretString' --output text 2>/dev/null); then
  note "Secret '$SECRET_NAME' already exists — its current values will be"
  note "offered as defaults instead of your local .env, where present."
else
  EXISTING_SECRET_JSON=""
fi

# _existing_secret_value NAME: pulls NAME out of EXISTING_SECRET_JSON without
# a JSON parser dependency - good enough for flat string values.
_existing_secret_value() {
  local name="$1"
  [[ -n "$EXISTING_SECRET_JSON" ]] || return 1
  printf '%s' "$EXISTING_SECRET_JSON" \
    | grep -o "\"$name\"[[:space:]]*:[[:space:]]*\"[^\"]*\"" \
    | sed -E "s/.*\"$name\"[[:space:]]*:[[:space:]]*\"([^\"]*)\"/\1/" \
    | head -n1
}

# ask_secret_with_default KEY "Prompt" DEFAULT is ask_secret, but the default
# can come from the secret's current value, not just $ENV_FILE.
ask_secret_with_default() {
  local key="$1" prompt="$2" default="$3" input
  if [[ -n "$default" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$default" ]] && input="$default"
  printf -v "$key" '%s' "$input"
}

say ""
say "SERVERLESS_ACCESS_KEY"
open_url "https://app.serverless.com/settings/accessKeys"
step "Create an access key (free at this org's size - billing only applies"
step "over \$2M/year revenue), then copy it."
default=$(_existing_secret_value SERVERLESS_ACCESS_KEY || true)
[[ -z "$default" ]] && default=$(_existing SERVERLESS_ACCESS_KEY || true)
ask_secret_with_default SERVERLESS_ACCESS_KEY "Paste the access key:" "$default"

say ""
say "REPLICATE_API_TOKEN"
open_url "https://replicate.com/account/api-tokens"
step "Copy an existing token, or create one."
default=$(_existing_secret_value REPLICATE_API_TOKEN || true)
[[ -z "$default" ]] && default=$(_existing REPLICATE_API_TOKEN || true)
ask_secret_with_default REPLICATE_API_TOKEN "Paste the token:" "$default"

say ""
say "REPLICATE_WEBHOOK_SECRET"
say "Needs REPLICATE_API_TOKEN from the step above. Fetching it for you..."
if [[ -n "${REPLICATE_API_TOKEN:-}" ]]; then
  if FETCHED=$(curl -fsS -H "Authorization: Bearer $REPLICATE_API_TOKEN" \
        "https://api.replicate.com/v1/webhooks/default/secret" 2>&1); then
    FETCHED_SECRET=$(printf '%s' "$FETCHED" | grep -o '"key"[[:space:]]*:[[:space:]]*"[^"]*"' | sed -E 's/.*"key"[[:space:]]*:[[:space:]]*"([^"]*)"/\1/')
    FETCHED_SECRET="${FETCHED_SECRET#whsec_}"
    note "Fetched from Replicate: ${FETCHED_SECRET:0:8}... (whsec_ prefix stripped)"
  else
    warn "Couldn't fetch it automatically:"
    note "$FETCHED"
    FETCHED_SECRET=""
  fi
else
  FETCHED_SECRET=""
fi
default=$(_existing_secret_value REPLICATE_WEBHOOK_SECRET || true)
[[ -z "$default" ]] && default=$(_existing REPLICATE_WEBHOOK_SECRET || true)
[[ -z "$default" ]] && default="$FETCHED_SECRET"
ask_secret_with_default REPLICATE_WEBHOOK_SECRET "Paste it (or accept the fetched value):" "$default"

say ""
say "MEDIA_PIPELINE_WEBHOOK_SECRET"
warn "Must be IDENTICAL to sureplug-backend's own MEDIA_PIPELINE_WEBHOOK_SECRET"
warn "value (already in its Secrets Manager secret sureplug-backend/$TARGET_STAGE)."
warn "Get it with: aws secretsmanager get-secret-value --secret-id sureplug-backend/$TARGET_STAGE --query SecretString --output text | grep -o '\"MEDIA_PIPELINE_WEBHOOK_SECRET\"[^,}]*'"
default=$(_existing_secret_value MEDIA_PIPELINE_WEBHOOK_SECRET || true)
[[ -z "$default" ]] && default=$(_existing MEDIA_PIPELINE_WEBHOOK_SECRET || true)
ask_secret_with_default MEDIA_PIPELINE_WEBHOOK_SECRET "Paste the same value backend uses:" "$default"

say ""
say "NOTIFICATION_DISPATCH_SECRET"
warn "Must be IDENTICAL to sureplug-backend's own NOTIFICATION_DISPATCH_SECRET"
warn "setting for this stage."
default=$(_existing_secret_value NOTIFICATION_DISPATCH_SECRET || true)
[[ -z "$default" ]] && default=$(_existing NOTIFICATION_DISPATCH_SECRET || true)
ask_secret_with_default NOTIFICATION_DISPATCH_SECRET "Paste the same value backend uses:" "$default"

VALUES_JSON="{"
first=true
for name in "${SECRET_VALUE_NAMES[@]}"; do
  value="${!name}"
  if [[ "$first" == true ]]; then first=false; else VALUES_JSON+=","; fi
  escaped=$(printf '%s' "$value" | sed 's/\\/\\\\/g; s/"/\\"/g')
  VALUES_JSON+="\"$name\":\"$escaped\""
done
VALUES_JSON+="}"

TMP_DIR=$(mktemp -d)
trap 'rm -rf "$TMP_DIR"' EXIT
SECRET_FILE="$TMP_DIR/secret.json"
printf '%s' "$VALUES_JSON" > "$SECRET_FILE"

if [[ -n "$EXISTING_SECRET_JSON" ]]; then
  if ! PUT_ERR=$(aws secretsmanager put-secret-value \
        --secret-id "$SECRET_NAME" \
        --secret-string "file://$SECRET_FILE" 2>&1); then
    warn "Failed to update secret '$SECRET_NAME':"
    note "$PUT_ERR"
    exit 1
  fi
  printf '  %s✓ updated%s secret %s\n' "$GREEN" "$RESET" "$SECRET_NAME"
else
  if ! CREATE_ERR=$(aws secretsmanager create-secret \
        --name "$SECRET_NAME" \
        --description "SurePlug serverless deploy config ($TARGET_STAGE)" \
        --secret-string "file://$SECRET_FILE" 2>&1); then
    warn "Failed to create secret '$SECRET_NAME':"
    note "$CREATE_ERR"
    exit 1
  fi
  printf '  %s✓ created%s secret %s\n' "$GREEN" "$RESET" "$SECRET_NAME"
fi

say ""
say "Next:"
say "  - Confirm the sureplug-serverless-deploy-$TARGET_STAGE IAM role has"
say "    deploy-config/ci-deploy-policy.json attached (its ReadDeploySecrets"
say "    statement is what lets CI read this secret)."
say "  - Re-run this script with the other stage whenever those values are"
say "    ready."

finish
