import { CellRecord, ImageRecord, RunRecord } from "./run-record";

export function buildReport(record: RunRecord): string {
  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Media pipeline run ${escapeHtml(record.runId)}</title>
<style>${STYLES}</style>
</head>
<body>
<header>
  <h1>Media pipeline &mdash; local Replicate run</h1>
  <p class="meta">${escapeHtml(record.startedAt)} &middot; ${
    record.images.length
  } image(s) &middot; ${record.models.length} model(s)</p>
</header>
${renderThresholds(record)}
${renderModels(record)}
${record.images.map(renderImage).join("\n")}
<footer>Generated by replicate-testing/run.ts. Stage logic is the real code from src/shared; only the Replicate transport and storage differ.</footer>
</body>
</html>
`;
}

function renderThresholds(record: RunRecord): string {
  const rows = Object.entries(record.thresholds)
    .map(
      ([key, value]) =>
        `<tr><th>${escapeHtml(key)}</th><td>${escapeHtml(String(value))}</td></tr>`
    )
    .join("");
  return `<section><h2>Thresholds this run used</h2><table class="kv">${rows}</table></section>`;
}

function renderModels(record: RunRecord): string {
  const rows = record.models
    .map((model) => {
      const warning =
        model.unknownFieldsSent.length > 0
          ? `<p class="warn">Sent fields this model does not declare: ${escapeHtml(
              model.unknownFieldsSent.join(", ")
            )}</p>`
          : "";
      return `<tr>
  <th>${escapeHtml(model.slug)}</th>
  <td><code>${
    model.endpoint === "version"
      ? `POST /predictions &middot; version ${escapeHtml(
          (model.versionId ?? "").slice(0, 12)
        )}&hellip;`
      : "POST /models/{owner}/{name}/predictions &middot; no public version"
  }</code></td>
  <td class="fields">${escapeHtml(model.inputFields.join(", ") || "unknown")}${warning}</td>
</tr>`;
    })
    .join("");
  return `<section><h2>Models, as Replicate actually describes them</h2>
<table class="models"><thead><tr><th>slug</th><th>how it is invoked</th><th>declared inputs</th></tr></thead><tbody>${rows}</tbody></table></section>`;
}

function renderImage(image: ImageRecord): string {
  const classification =
    image.classification === null
      ? `<span class="pill muted">classify skipped</span>`
      : `<span class="pill ${
          image.expectedClassification === null ||
          image.expectedClassification === image.classification
            ? "ok"
            : "bad"
        }">${escapeHtml(image.classification)}${
          image.expectedClassification &&
          image.expectedClassification !== image.classification
            ? ` &ne; expected ${escapeHtml(image.expectedClassification)}`
            : ""
        }</span>`;

  const raw = image.classificationRaw
    ? `<p class="raw">model said: ${escapeHtml(
        image.classificationRaw.slice(0, 200)
      )}</p>`
    : "";

  return `<section class="image">
<h2>${escapeHtml(image.filename)}</h2>
<p class="tests">${escapeHtml(image.tests)}</p>
<div class="summary">
  <figure class="original">
    <img src="${escapeHtml(image.originalPath)}" alt="original">
    <figcaption>${image.width}&times;${image.height}</figcaption>
  </figure>
  <dl>
    <dt>blur score</dt><dd>${image.blurScore.toFixed(1)} <span class="pill ${
      image.isBlurry ? "bad" : "ok"
    }">${image.isBlurry ? "too blurry" : "sharp enough"}</span></dd>
    <dt>classification</dt><dd>${classification}${
      image.classificationModelLabel
        ? ` <span class="muted">(${escapeHtml(
            image.classificationModelLabel
          )})</span>`
        : ""
    }${raw}</dd>
  </dl>
</div>
${
  image.cells.length === 0
    ? `<p class="muted">No background-removal runs for this image${
        image.classification === "KEEP"
          ? " &mdash; KEEP means production renders variants straight from the raw upload."
          : "."
      }</p>`
    : `<div class="cells">${image.cells.map(renderCell).join("")}</div>`
}
</section>`;
}

function renderCell(cell: CellRecord): string {
  if (cell.error) {
    return `<article class="cell"><h3>${escapeHtml(
      cell.modelLabel
    )}</h3><p class="warn">${escapeHtml(cell.error)}</p></article>`;
  }

  const stages = [
    stageFigure("cutout", cell.cutoutPath, true),
    stageFigure("cropped", cell.croppedPath, true),
    stageFigure("master", cell.masterPath, false),
    stageFigure("upscaled", cell.upscale?.path ?? null, false),
  ]
    .filter(Boolean)
    .join("");

  const alphaWarning =
    cell.hasAlphaChannel === false
      ? `<p class="warn">Output had no alpha channel. This model returned a flattened image, so the mask could not be measured &mdash; set its format/background inputs in config.ts.</p>`
      : "";

  const crop =
    cell.cropPlan?.outcome === "NEEDS_REUPLOAD"
      ? `<span class="pill bad">${escapeHtml(cell.cropPlan.reason)}</span>`
      : `<span class="pill ok">crop ok</span>`;

  return `<article class="cell">
<h3>${escapeHtml(cell.modelLabel)}</h3>
<p class="stats">
  ${crop}
  <span>coverage ${
    cell.coverageRatio === null ? "n/a" : cell.coverageRatio.toFixed(4)
  }</span>
  ${
    cell.masterWidth
      ? `<span>master ${cell.masterWidth}&times;${cell.masterHeight}</span>`
      : ""
  }
  ${
    cell.needsUpscale === null
      ? ""
      : `<span class="pill ${
          cell.needsUpscale ? "info" : "muted"
        }">needsUpscale ${cell.needsUpscale}</span>`
  }
  ${
    cell.removeBackground
      ? `<span class="muted">${(
          cell.removeBackground.wallClockMs / 1000
        ).toFixed(1)}s wall${
          cell.removeBackground.predictTimeSeconds
            ? ` / ${cell.removeBackground.predictTimeSeconds.toFixed(
                1
              )}s predict`
            : ""
        }</span>`
      : ""
  }
</p>
${alphaWarning}
<div class="stages">${stages}</div>
${
  cell.upscale
    ? `<p class="stats"><span class="pill info">upscaled by ${escapeHtml(
        cell.upscale.modelLabel
      )}</span><span>${cell.upscale.width}&times;${
        cell.upscale.height
      }</span></p>`
    : ""
}
${
  cell.variants.length > 0
    ? `<details><summary>${
        cell.variants.length
      } variants</summary><table class="variants">${cell.variants
        .map(
          (variant) =>
            `<tr><th>${escapeHtml(variant.name)} ${escapeHtml(
              variant.format
            )}</th><td>${variant.width}&times;${variant.height}</td><td>${(
              variant.sizeBytes / 1024
            ).toFixed(0)} KB</td><td><a href="${escapeHtml(
              variant.filename
            )}">open</a></td></tr>`
        )
        .join("")}</table></details>`
    : ""
}
</article>`;
}

function stageFigure(
  label: string,
  path: string | null,
  checkered: boolean
): string {
  if (!path) return "";
  return `<figure class="${checkered ? "checkered" : ""}">
<a href="${escapeHtml(path)}"><img src="${escapeHtml(path)}" alt="${escapeHtml(
    label
  )}" loading="lazy"></a>
<figcaption>${escapeHtml(label)}</figcaption>
</figure>`;
}

function escapeHtml(value: string): string {
  return value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

const STYLES = `
:root {
  --bg: #ffffff; --fg: #16181d; --muted: #6b7280; --line: #e3e6ea;
  --card: #f7f8fa; --ok: #0f7b4f; --okbg: #e3f5ec;
  --bad: #a3252a; --badbg: #fdeaea; --info: #1f5fa8; --infobg: #e7f0fb;
}
@media (prefers-color-scheme: dark) {
  :root:not([data-theme="light"]) {
    --bg: #14161a; --fg: #e8eaed; --muted: #9aa2ad; --line: #2c3036;
    --card: #1c1f24; --ok: #6ddfa6; --okbg: #15301f;
    --bad: #ff9b9b; --badbg: #3a1b1d; --info: #8fc1f5; --infobg: #16283d;
  }
}
:root[data-theme="dark"] {
  --bg: #14161a; --fg: #e8eaed; --muted: #9aa2ad; --line: #2c3036;
  --card: #1c1f24; --ok: #6ddfa6; --okbg: #15301f;
  --bad: #ff9b9b; --badbg: #3a1b1d; --info: #8fc1f5; --infobg: #16283d;
}
* { box-sizing: border-box; }
body {
  margin: 0; padding: 0 16px 64px; background: var(--bg); color: var(--fg);
  font: 15px/1.5 -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
  max-width: 1400px; margin-inline: auto;
}
header { padding: 32px 0 8px; }
h1 { font-size: 24px; margin: 0 0 4px; }
h2 { font-size: 18px; margin: 32px 0 4px; }
h3 { font-size: 15px; margin: 0 0 8px; }
.meta, .tests, .muted, .raw { color: var(--muted); }
.tests { margin: 0 0 16px; }
.raw { font-size: 13px; margin: 4px 0 0; font-family: ui-monospace, monospace; }
section { border-top: 1px solid var(--line); padding-top: 8px; }
table { border-collapse: collapse; font-size: 14px; }
table.kv th, table.models th { text-align: left; font-weight: 600; padding: 4px 16px 4px 0; vertical-align: top; }
table.kv td, table.models td { padding: 4px 16px 4px 0; vertical-align: top; }
table.models { width: 100%; }
table.models thead th { border-bottom: 1px solid var(--line); color: var(--muted); font-weight: 500; }
.fields { font-family: ui-monospace, monospace; font-size: 13px; }
code { font-size: 13px; }
.summary { display: flex; gap: 24px; align-items: flex-start; flex-wrap: wrap; }
.summary .original img { max-width: 220px; max-height: 220px; border: 1px solid var(--line); border-radius: 6px; display: block; }
figure { margin: 0; }
figcaption { font-size: 12px; color: var(--muted); margin-top: 4px; }
dl { margin: 0; display: grid; grid-template-columns: auto 1fr; gap: 4px 16px; align-items: start; }
dt { color: var(--muted); }
dd { margin: 0; }
.cells { display: grid; grid-template-columns: repeat(auto-fit, minmax(320px, 1fr)); gap: 16px; margin-top: 16px; }
.cell { background: var(--card); border: 1px solid var(--line); border-radius: 8px; padding: 12px; }
.stats { display: flex; flex-wrap: wrap; gap: 8px; align-items: center; margin: 0 0 8px; font-size: 13px; }
.stages { display: flex; gap: 8px; flex-wrap: wrap; }
.stages figure { flex: 1 1 120px; }
.stages img { width: 100%; height: auto; max-height: 200px; object-fit: contain; border: 1px solid var(--line); border-radius: 4px; display: block; }
.checkered img {
  background-image: linear-gradient(45deg, #c9ccd1 25%, transparent 25%),
    linear-gradient(-45deg, #c9ccd1 25%, transparent 25%),
    linear-gradient(45deg, transparent 75%, #c9ccd1 75%),
    linear-gradient(-45deg, transparent 75%, #c9ccd1 75%);
  background-size: 16px 16px;
  background-position: 0 0, 0 8px, 8px -8px, -8px 0;
}
.pill { display: inline-block; padding: 1px 8px; border-radius: 999px; font-size: 12px; font-weight: 600; }
.pill.ok { background: var(--okbg); color: var(--ok); }
.pill.bad { background: var(--badbg); color: var(--bad); }
.pill.info { background: var(--infobg); color: var(--info); }
.pill.muted { background: var(--line); color: var(--muted); }
.warn { background: var(--badbg); color: var(--bad); padding: 8px 10px; border-radius: 6px; font-size: 13px; margin: 8px 0; }
details { margin-top: 8px; font-size: 13px; }
summary { cursor: pointer; color: var(--muted); }
table.variants th { font-weight: 500; }
a { color: inherit; }
footer { margin-top: 48px; padding-top: 16px; border-top: 1px solid var(--line); color: var(--muted); font-size: 13px; }
@media (max-width: 600px) { .cells { grid-template-columns: 1fr; } }
`;
